num_workers: 8
envs_per_worker: 2
gamma: 0.99
lam: 0.95
clip_eps_start: 0.2
clip_eps_max: 0.2
clip_eps_min: 0.05
lr: 0.0003
entropy_coef: 0.001
episodes: 1000
update_epochs: 5
batch_size: 512
steps_per_env: 128
kl_treshold: 0.03

