defaults:
  - env: isaac_go1_nav
  - ppo: default
  - logging: default
  - checkpoint: default
  - experiment: default

model:
  # реальные размеры наблюдений/действий env
  obs_dim: 24
  act_dim: 8

env:
  kind: isaaclab     # "gym" | "isaaclab"
  name: Go1Nav-v0  # если kind=gym — это gym_id; если kind=isaaclab — просто строка-тег

experiment:
  name: appo_demo

